services:
  - type: web
    name: zap-daemon
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    healthCheckPath: /JSON/core/view/version/
    envVars:
      - key: PORT
        value: 8080
